;  /$$$$$$           /$$           /$$                          
; |_  $$_/          |__/          | $$                          
;   | $$   /$$$$$$$  /$$  /$$$$$$ | $$       /$$   /$$  /$$$$$$ 
;   | $$  | $$__  $$| $$ /$$__  $$| $$      | $$  | $$ |____  $$
;   | $$  | $$  \ $$| $$| $$  \ $$| $$      | $$  | $$  /$$$$$$$
;   | $$  | $$  | $$| $$| $$  | $$| $$      | $$  | $$ /$$__  $$
;  /$$$$$$| $$  | $$| $$|  $$$$$$/| $$$$$$$$|  $$$$$$/|  $$$$$$$
; |______/|__/  |__/|__/ \______/ |________/ \______/  \_______/
;
;
;           Version: 1.0.0      author: n11kol11c

[globals]
encoding=utf-8
devbuild=inio-lua-1.0.0
